import { lazy } from 'react';
import {
  Braces,
  KeyRound,
  Hash,
  Regex,
  Binary,
  Fingerprint,
  Palette,
  Link2,
  Clock,
  Key,
  FileDiff,
  CalendarClock,
  Type,
  QrCode,
  FileCode2,
} from 'lucide-react';
import type { Tool, ToolCategory, CategoryInfo } from '@/types';

export const CATEGORIES: CategoryInfo[] = [
  { id: 'converters', label: 'Converters', iconName: 'ArrowRightLeft', description: 'JSON, color, timestamp converters' },
  { id: 'crypto', label: 'Crypto & Auth', iconName: 'Shield', description: 'Hashes, JWT decoders, encryption' },
  { id: 'encoding', label: 'Encoding', iconName: 'Binary', description: 'Base64, URL encoder/decoder' },
  { id: 'generators', label: 'Generators', iconName: 'Sparkles', description: 'UUID, passwords, QR codes, crons' },
  { id: 'text', label: 'Text & Diff', iconName: 'FileText', description: 'Regex, diff checkers, lorem ipsum' },
  { id: 'web', label: 'Web & Dev', iconName: 'Globe', description: 'Markdown preview, web tools' },
];

export const TOOLS: Tool[] = [
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, minify, validate, sort keys, and inspect JSON documents.',
    category: 'converters',
    keywords: ['json', 'prettify', 'format', 'minify', 'validate', 'beautify', 'sort keys'],
    icon: Braces,
    path: '/json-formatter',
    component: lazy(() => import('@/features/json-formatter')),
    shortcut: 'J',
    popular: true,
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode header, payload claims, and verify expiry dates of JSON Web Tokens.',
    category: 'crypto',
    keywords: ['jwt', 'token', 'decode', 'bearer', 'auth', 'claims', 'expiration'],
    icon: KeyRound,
    path: '/jwt-decoder',
    component: lazy(() => import('@/features/jwt-decoder')),
    shortcut: 'W',
    popular: true,
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate SHA-256, SHA-512, SHA-384, and SHA-1 hashes for text and files.',
    category: 'crypto',
    keywords: ['hash', 'sha256', 'sha512', 'sha1', 'checksum', 'crypto', 'digest'],
    icon: Hash,
    path: '/hash-generator',
    component: lazy(() => import('@/features/hash-generator')),
    shortcut: 'H',
    popular: true,
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions with real-time match groups and flags.',
    category: 'text',
    keywords: ['regex', 'regular expression', 'pattern', 'test', 'match', 'eval'],
    icon: Regex,
    path: '/regex-tester',
    component: lazy(() => import('@/features/regex-tester')),
    shortcut: 'R',
    popular: true,
  },
  {
    id: 'base64',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode UTF-8 text and binary files to Base64 with URL-safe format.',
    category: 'encoding',
    keywords: ['base64', 'b64', 'encode', 'decode', 'binary', 'ascii'],
    icon: Binary,
    path: '/base64',
    component: lazy(() => import('@/features/base64')),
    shortcut: 'B',
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Bulk generate RFC 4122 compliant UUID v4 identifiers with custom formats.',
    category: 'generators',
    keywords: ['uuid', 'guid', 'unique id', 'v4', 'random id'],
    icon: Fingerprint,
    path: '/uuid-generator',
    component: lazy(() => import('@/features/uuid-generator')),
    shortcut: 'U',
    popular: true,
  },
  {
    id: 'color-picker',
    name: 'Color Converter',
    description: 'Convert HEX, RGB, HSL values and check WCAG contrast ratios.',
    category: 'converters',
    keywords: ['color', 'hex', 'rgb', 'contrast', 'wcag', 'palette'],
    icon: Palette,
    path: '/color-picker',
    component: lazy(() => import('@/features/color-picker')),
    shortcut: 'C',
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder / Decoder',
    description: 'Encode/decode URI components and inspect query parameters in detail.',
    category: 'encoding',
    keywords: ['url', 'uri', 'encode', 'decode', 'query', 'params', 'query string'],
    icon: Link2,
    path: '/url-encoder',
    component: lazy(() => import('@/features/url-encoder')),
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert between Unix epoch timestamps (seconds/ms) and ISO dates.',
    category: 'converters',
    keywords: ['timestamp', 'unix', 'epoch', 'date', 'time', 'iso', 'clock'],
    icon: Clock,
    path: '/timestamp-converter',
    component: lazy(() => import('@/features/timestamp-converter')),
    shortcut: 'T',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate high-entropy cryptographic passwords with entropy calculation.',
    category: 'generators',
    keywords: ['password', 'generator', 'random', 'secret', 'entropy', 'passphrase'],
    icon: Key,
    path: '/password-generator',
    component: lazy(() => import('@/features/password-generator')),
    shortcut: 'P',
  },
  {
    id: 'diff-checker',
    name: 'Diff Checker',
    description: 'Compare text and code side-by-side with line additions and modifications.',
    category: 'text',
    keywords: ['diff', 'compare', 'difference', 'code diff', 'text diff'],
    icon: FileDiff,
    path: '/diff-checker',
    component: lazy(() => import('@/features/diff-checker')),
  },
  {
    id: 'cron-parser',
    name: 'Cron Parser',
    description: 'Human-readable description and presets for 5-part cron schedules.',
    category: 'generators',
    keywords: ['cron', 'schedule', 'tab', 'cronjob', 'parser'],
    icon: CalendarClock,
    path: '/cron-parser',
    component: lazy(() => import('@/features/cron-parser')),
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text paragraphs, sentences, and words for layouts.',
    category: 'text',
    keywords: ['lorem', 'ipsum', 'placeholder', 'dummy text', 'filler'],
    icon: Type,
    path: '/lorem-ipsum',
    component: lazy(() => import('@/features/lorem-ipsum')),
  },
  {
    id: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Generate high-resolution QR codes for links, text, and Wi-Fi credentials.',
    category: 'generators',
    keywords: ['qr', 'qrcode', 'barcode', 'generator', 'download png'],
    icon: QrCode,
    path: '/qr-code-generator',
    component: lazy(() => import('@/features/qr-code-generator')),
    shortcut: 'Q',
  },
  {
    id: 'markdown-preview',
    name: 'Markdown Preview',
    description: 'Live split-view editor for Markdown with GitHub Flavored Markdown (GFM).',
    category: 'web',
    keywords: ['markdown', 'md', 'gfm', 'editor', 'preview', 'readme'],
    icon: FileCode2,
    path: '/markdown-preview',
    component: lazy(() => import('@/features/markdown-preview')),
    shortcut: 'M',
  },
];

export function getToolById(id: string): Tool | undefined {
  return TOOLS.find((t) => t.id === id);
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return TOOLS.filter((t) => t.category === category);
}
